export enum NewsType {
    NEWS_SOON_OVERDUE_BOOKINGS = "NEWS_SOON_OVERDUE_BOOKINGS",
    NEWS_OVERDUE_BOOKINGS = "NEWS_OVERDUE_BOOKINGS",
    NEWS_NEW_ENTITY = "NEWS_NEW_ENTITY",
    NEWS_BOOKING_STARTS_TODAY = "NEWS_BOOKING_STARTS_TODAY"
  }